# Generated by Django 3.0.4 on 2020-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
